# Site settings
title: Blogs and Learning Notes 
email: 
description: 
baseurl: "/blog"
url: "https://xuyangcao.github.io"
courseurl:
twitter_username:
github_username:

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge