# Site settings
title: Blog and Learning Notes 
email: 
description: 
baseurl: ""
url: "https://xuyangcao.github.io/blog"
courseurl:
twitter_username:
github_username:

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge