# Site settings
title: Xuyang Cao's Blog
email: caoxuyang@bjtu.edu.cn
description: ""
baseurl: ""
url: "http://xuyangcao.github.io/blog/"
courseurl: ""
twitter_username: xuyangcao
github_username: xuyangcao

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge